#!/usr/bin/env python
# encoding: utf-8
#
# Copyright  (c) 2014 deanishe@deanishe.net
#
# MIT Licence. See http://opensource.org/licenses/MIT
#
# Created on 2014-02-25
#

"""Variables required by more than one script."""

import os
import shutil

# ----------------------------------------------------------------------
# Keywords assigned to Alfred Keywords/Script Filters
# ----------------------------------------------------------------------
KEYWORD_CONVERT = 'conv'
KEYWORD_SETTINGS = 'convinfo'

# ----------------------------------------------------------------------
# Result display
# ----------------------------------------------------------------------
DECIMAL_PLACES = int(os.getenv('DECIMAL_PLACES') or '2')
DECIMAL_SEPARATOR = os.getenv('DECIMAL_SEPARATOR') or '.'
THOUSANDS_SEPARATOR = os.getenv('THOUSANDS_SEPARATOR') or ''

COPY_UNIT = os.getenv('COPY_UNIT', '') not in ('', '0')

# ----------------------------------------------------------------------
# Currency settings
# ----------------------------------------------------------------------
# Update interval (default 6 hours)
CURRENCY_CACHE_AGE = int(os.getenv('UPDATE_INTERVAL') or '360') * 60

CURRENCY_CACHE_NAME = 'exchange_rates'
REFERENCE_CURRENCY = 'EUR'
YAHOO_BASE_URL = 'https://download.finance.yahoo.com/d/quotes.csv?f=sl1&s={}'
CRYPTO_COMPARE_BASE_URL = 'https://min-api.cryptocompare.com/data/price?fsym={}&tsyms={}'
SYMBOLS_PER_REQUEST = 20

# ----------------------------------------------------------------------
# Unit definition files
# ----------------------------------------------------------------------
CUSTOM_DEFINITIONS_FILENAME = 'unit_definitions.txt'
BUILTIN_UNIT_DEFINITIONS = os.path.join(os.path.dirname(__file__),
                                        CUSTOM_DEFINITIONS_FILENAME)

ACTIVE_CURRENCIES_FILENAME = 'active_currencies.txt'

# with open(os.path.join(os.path.dirname(__file__),
#                        'currencies.tsv'), 'rb') as fp:
#     reader = csv.reader(fp, delimiter=b'\t')
#     for sym, name in reader:
#         sym = unicode(sym, 'utf-8')
#         name = unicode(name, 'utf-8')
#         CURRENCIES[sym] = name

CURRENCIES = {
    'AED': u'UAE Dirham',
    'AFN': u'Afghani',
    'ALL': u'Lek',
    'AMD': u'Armenian Dram',
    'ANG': u'Netherlands Antillean Guilder',
    'AOA': u'Kwanza',
    'ARS': u'Argentine Peso',
    'AUD': u'Australian Dollar',
    'AWG': u'Aruban Florin',
    'AZN': u'Azerbaijanian Manat',
    'BAM': u'Convertible Mark',
    'BBD': u'Barbados Dollar',
    'BDT': u'Taka',
    'BGN': u'Bulgarian Lev',
    'BHD': u'Bahraini Dinar',
    'BIF': u'Burundi Franc',
    'BMD': u'Bermudian Dollar',
    'BND': u'Brunei Dollar',
    'BOB': u'Boliviano',
    'BRL': u'Brazilian Real',
    'BSD': u'Bahamian Dollar',
    'BTN': u'Ngultrum',
    'BWP': u'Pula',
    'BYR': u'Belarussian Ruble',
    'BZD': u'Belize Dollar',
    'CAD': u'Canadian Dollar',
    'CDF': u'Congolese Franc',
    'CHF': u'Swiss Franc',
    'CLF': u'Unidad de Fomento',
    'CLP': u'Chilean Peso',
    'CNY': u'Yuan Renminbi',
    'COP': u'Colombian Peso',
    'CRC': u'Costa Rican Colon',
    'CUP': u'Cuban Peso',
    'CVE': u'Cabo Verde Escudo',
    'CZK': u'Czech Koruna',
    'DJF': u'Djibouti Franc',
    'DKK': u'Danish Krone',
    'DOP': u'Dominican Peso',
    'DZD': u'Algerian Dinar',
    'EGP': u'Egyptian Pound',
    'ERN': u'Nakfa',
    'ETB': u'Ethiopian Birr',
    'EUR': u'Euro',
    'FJD': u'Fiji Dollar',
    'FKP': u'Falkland Islands Pound',
    'GBP': u'Pound Sterling',
    'GEL': u'Lari',
    'GHS': u'Ghana Cedi',
    'GIP': u'Gibraltar Pound',
    'GMD': u'Dalasi',
    'GNF': u'Guinea Franc',
    'GTQ': u'Quetzal',
    'GYD': u'Guyana Dollar',
    'HKD': u'Hong Kong Dollar',
    'HNL': u'Lempira',
    'HRK': u'Kuna',
    'HTG': u'Gourde',
    'HUF': u'Forint',
    'IDR': u'Rupiah',
    'ILS': u'New Israeli Sheqel',
    'INR': u'Indian Rupee',
    'IQD': u'Iraqi Dinar',
    'IRR': u'Iranian Rial',
    'ISK': u'Iceland Krona',
    'JMD': u'Jamaican Dollar',
    'JOD': u'Jordanian Dinar',
    'JPY': u'Yen',
    'KES': u'Kenyan Shilling',
    'KGS': u'Som',
    'KHR': u'Riel',
    'KMF': u'Comoro Franc',
    'KPW': u'North Korean Won',
    'KRW': u'Won',
    'KWD': u'Kuwaiti Dinar',
    'KYD': u'Cayman Islands Dollar',
    'KZT': u'Tenge',
    'LAK': u'Kip',
    'LBP': u'Lebanese Pound',
    'LKR': u'Sri Lanka Rupee',
    'LRD': u'Liberian Dollar',
    'LSL': u'Loti',
    'LYD': u'Libyan Dinar',
    'MAD': u'Moroccan Dirham',
    'MDL': u'Moldovan Leu',
    'MGA': u'Malagasy Ariary',
    'MKD': u'Denar',
    'MMK': u'Kyat',
    'MNT': u'Tugrik',
    'MOP': u'Pataca',
    'MRO': u'Ouguiya',
    'MUR': u'Mauritius Rupee',
    'MVR': u'Rufiyaa',
    'MWK': u'Kwacha',
    'MXN': u'Mexican Peso',
    'MXV': u'Mexican Unidad de Inversion (UDI)',
    'MYR': u'Malaysian Ringgit',
    'MZN': u'Mozambique Metical',
    'NAD': u'Namibia Dollar',
    'NGN': u'Naira',
    'NIO': u'Cordoba Oro',
    'NOK': u'Norwegian Krone',
    'NPR': u'Nepalese Rupee',
    'NZD': u'New Zealand Dollar',
    'OMR': u'Rial Omani',
    'PAB': u'Balboa',
    'PEN': u'Nuevo Sol',
    'PGK': u'Kina',
    'PHP': u'Philippine Peso',
    'PKR': u'Pakistan Rupee',
    'PLN': u'Zloty',
    'PYG': u'Guarani',
    'QAR': u'Qatari Rial',
    'RON': u'Romanian Leu',
    'RSD': u'Serbian Dinar',
    'RUB': u'Russian Ruble',
    'RWF': u'Rwanda Franc',
    'SAR': u'Saudi Riyal',
    'SBD': u'Solomon Islands Dollar',
    'SCR': u'Seychelles Rupee',
    'SDG': u'Sudanese Pound',
    'SEK': u'Swedish Krona',
    'SGD': u'Singapore Dollar',
    'SHP': u'Saint Helena Pound',
    'SLL': u'Leone',
    'SOS': u'Somali Shilling',
    'SRD': u'Surinam Dollar',
    'STD': u'Dobra',
    'SVC': u'El Salvador Colon',
    'SYP': u'Syrian Pound',
    'SZL': u'Lilangeni',
    'THB': u'Baht',
    'TJS': u'Somoni',
    'TMT': u'Turkmenistan New Manat',
    'TND': u'Tunisian Dinar',
    'TOP': u'Pa’anga',
    'TRY': u'Turkish Lira',
    'TTD': u'Trinidad and Tobago Dollar',
    'TWD': u'New Taiwan Dollar',
    'TZS': u'Tanzanian Shilling',
    'UAH': u'Hryvnia',
    'UGX': u'Uganda Shilling',
    'USD': u'US Dollar',
    'UYU': u'Peso Uruguayo',
    'UZS': u'Uzbekistan Sum',
    'VEF': u'Bolivar',
    'VND': u'Dong',
    'VUV': u'Vatu',
    'WST': u'Tala',
    'XAF': u'CFA Franc BEAC',
    'XAG': u'Silver',
    'XAU': u'Gold',
    'XCD': u'East Caribbean Dollar',
    'XDR': u'SDR (Special Drawing Right)',
    'XOF': u'CFA Franc BCEAO',
    'XPD': u'Palladium',
    'XPF': u'CFP Franc',
    'XPT': u'Platinum',
    'YER': u'Yemeni Rial',
    'ZAR': u'Rand',
    'ZMW': u'Zambian Kwacha',
    'ZWL': u'Zimbabwe Dollar',
}

CRYPTO_CURRENCIES = {
    # '007': u'007 coin',  # Pint doesn't accept units that begin with digits
    # '1337': u'1337',  # Pint doesn't accept units that begin with digits
    # '1CR': u'1Credit',  # Pint doesn't accept units that begin with digits
    # '1ST': u'FirstBlood',  # Pint doesn't accept units that begin with digits
    # '2015': u'2015 coin',  # Pint doesn't accept units that begin with digits
    # '2BACCO': u'2BACCO Coin',  # Pint doesn't accept units that begin with digits
    # '2GIVE': u'2GiveCoin',  # Pint doesn't accept units that begin with digits
    # '32BIT': u'32Bitcoin',  # Pint doesn't accept units that begin with digits
    # '365': u'365Coin',  # Pint doesn't accept units that begin with digits
    # '404': u'404Coin',  # Pint doesn't accept units that begin with digits
    # '42': u'42 Coin',  # Pint doesn't accept units that begin with digits
    # '611': u'SixEleven',  # Pint doesn't accept units that begin with digits
    # '808': u'808',  # Pint doesn't accept units that begin with digits
    # '888': u'Octocoin',  # Pint doesn't accept units that begin with digits
    # '8BIT': u'8BIT Coin',  # Pint doesn't accept units that begin with digits
    'ABY': u'ArtByte',
    'AC': u'Asia Coin',
    'ACES': u'AcesCoin',
    'ACID': u'AcidCoin',
    'ACN': u'AvonCoin',
    'ACOIN': u'ACoin',
    'ACP': u'Anarchists Prime',
    'ADC': u'AudioCoin',
    'ADCN': u'Asiadigicoin',
    'ADN': u'Aiden',
    'ADX': u'AdEx',
    'ADZ': u'Adzcoin',
    'AEC': u'AcesCoin',
    'AEON': u'AeonCoin',
    'AERO': u'Aero Coin',
    'AGS': u'Aegis',
    'AIB': u'AdvancedInternetBlock',
    'AIR': u'Aircoin',
    'ALC': u'Arab League Coin',
    'ALEX': u'Alexandrite',
    'ALF': u'AlphaCoin',
    'ALN': u'AlienCoin',
    'AM': u'AeroMe',
    'AMBER': u'AmberCoin',
    'AMC': u'AmericanCoin',
    'AMIS': u'AMIS',
    'AMP': u'Synereo',
    'AMS': u'Amsterdam Coin',
    'ANAL': u'AnalCoin',
    'ANC': u'Anoncoin',
    'AND': u'AndromedaCoin',
    'ANS': u'Antshares',
    'ANT': u'Aragon',
    'ANTI': u'Anti Bitcoin',
    'APC': u'AlpaCoin',
    'APEX': u'ApexCoin',
    'APT': u'Aptcoin',
    'APX': u'Apx',
    'ARB': u'Arbit Coin',
    'ARCH': u'ArchCoin',
    'ARCO': u'AquariusCoin',
    'ARDR': u'Ardor',
    'ARG': u'Argentum',
    'ARGUS': u'ArgusCoin',
    'ARI': u'AriCoin',
    'ARK': u'ARK',
    'ARM': u'Armory Coin',
    'ARPA': u'ArpaCoin',
    'ASAFE': u'Allsafe',
    'ASN': u'Ascension Coin',
    'AST': u'Astral',
    'ATM': u'Autumncoin',
    'ATMS': u'Atmos',
    'ATOM': u'Atomic Coin',
    'ATX': u'ArtexCoin',
    'AUR': u'Aurora Coin',
    'AV': u'Avatar Coin',
    'AVT': u'AventCoin',
    'AXIOM': u'Axiom Coin',
    'AXR': u'AXRON',
    'B3': u'B3 Coin',
    'B@': u'BankCoin',
    'BAC': u'BitalphaCoin',
    'BAN': u'Babes and Nerds',
    'BASH': u'LuckChain',
    'BAT': u'Basic Attention Token',
    'BAY': u'BitBay',
    'BBCC': u'BaseballCardCoin',
    'BBR': u'Boolberry',
    'BCAP': u'Blockchain Capital',
    'BCCOIN': u'BitConnect Coin',
    'BCF': u'BitcoinFast',
    'BCN': u'ByteCoin',
    'BCR': u'BitCredit',
    'BCX': u'BattleCoin',
    'BCY': u'BitCrystals',
    'BELA': u'BelaCoin',
    'BEN': u'Benjamins',
    'BENJI': u'BenjiRolls',
    'BERN': u'BERNcash',
    'BEST': u'BestChain',
    'BET': u'BetaCoin',
    'BFX': u'BitFinex Tokens',
    'BHC': u'BighanCoin',
    'BIC': u'Bikercoins',
    'BIGUP': u'BigUp',
    'BIOB': u'BioBar',
    'BIOS': u'BiosCrypto',
    'BIP': u'BipCoin',
    'BIT16': u'16BitCoin',
    'BITB': u'BitBean',
    'BITCNY': u'bitCNY',
    'BITOK': u'BitOKX',
    'BITS': u'BitstarCoin',
    'BITUSD': u'bitUSD',
    'BITZ': u'Bitz Coin',
    'BLAZR': u'BlazerCoin',
    'BLC': u'BlakeCoin',
    'BLITZ': u'BlitzCoin',
    'BLK': u'BlackCoin',
    'BLOCK': u'BlockNet',
    'BLRY': u'BillaryCoin',
    'BLU': u'BlueCoin',
    'BM': u'BitMoon',
    'BNB': u'Boats and Bitches',
    'BNT': u'Bancor Network Token',
    'BNX': u'BnrtxCoin',
    'BOB': u'Bob Coin',
    'BOLI': u'BolivarCoin',
    'BOMB': u'BombCoin',
    'BON': u'BonesCoin',
    'BOOM': u'BOOM Coin',
    'BOS': u'BOScoin',
    'BOSON': u'BosonCoin',
    'BOSS': u'BitBoss',
    'BOST': u'BoostCoin',
    'BQC': u'BQCoin',
    'BQX': u'Bitquence',
    'BRAIN': u'BrainCoin',
    'BRDD': u'BeardDollars',
    'BRK': u'BreakoutCoin',
    'BRONZ': u'BitBronze',
    'BS': u'BlackShadowCoin',
    'BSC': u'BowsCoin',
    'BSD': u'BitSend',
    'BST': u'BitStone',
    'BSTAR': u'Blackstar',
    'BSTK': u'BattleStake',
    'BSTY': u'GlobalBoost',
    'BTA': u'Bata',
    'BTB': u'BitBar',
    'BTC': u'Bitcoin',
    'BTCD': u'BitcoinDark',
    'BTCR': u'BitCurrency',
    'BTCRY': u'BitCrystal',
    'BTCS': u'Bitcoin Scrypt',
    'BTD': u'Bitcloud',
    'BTE': u'ByteCoin',
    'BTG': u'BitGem',
    'BTLC': u'BitLuckCoin',
    'BTM': u'BitMark',
    'BTMI': u'BitMiles',
    'BTQ': u'BitQuark',
    'BTS': u'Bitshares',
    'BTTF': u'Coin to the Future',
    'BTX': u'BitcoinTX',
    'BTZ': u'BitzCoin',
    'BUCKS': u'SwagBucks',
    'BUK': u'CryptoBuk',
    'BURST': u'BurstCoin',
    'BUZZ': u'BuzzCoin',
    'BVC': u'BeaverCoin',
    'BXC': u'Bitcedi',
    'BXT': u'BitTokens',
    'BYC': u'ByteCent',
    'C2': u'Coin.2',
    'CAB': u'CabbageUnit',
    'CACH': u'Cachecoin',
    'CAIX': u'CAIx',
    'CALC': u'CaliphCoin',
    'CAM': u'Camcoin',
    'CANN': u'CannabisCoin',
    'CAP': u'BottleCaps',
    'CARBON': u'Carboncoin',
    'CASH': u'CashCoin',
    'CAT': u'Catcoin',
    'CBD': u'CBD Crystals',
    'CBX': u'CryptoBullion',
    'CC': u'CyberCoin',
    'CCN': u'CannaCoin',
    'CCRB': u'CryptoCarbon',
    'CCX': u'CoolDarkCoin',
    'CDN': u'Canada eCoin',
    'CELL': u'SolarFarm',
    'CESC': u'Crypto Escudo',
    'CETI': u'CETUS Coin',
    'CF': u'Californium',
    'CFC': u'CoffeeCoin',
    'CFI': u'Cofound.it',
    'CFT': u'CryptoForecast',
    'CGA': u'Cryptographic Anomaly',
    'CHA': u'Charity Coin',
    'CHAO': u'23 Skidoo',
    'CHASH': u'CleverHash',
    'CHAT': u'ChatCoin',
    'CHC': u'ChainCoin',
    'CHESS': u'ChessCoin',
    'CHIEF': u'TheChiefCoin',
    'CHILD': u'ChildCoin',
    'CHIP': u'Chip',
    'CHOOF': u'ChoofCoin',
    'CIN': u'CinderCoin',
    'CINNI': u'CINNICOIN',
    'CIR': u'CircuitCoin',
    'CIRC': u'CryptoCircuits',
    'CJ': u'CryptoJacks',
    'CJC': u'CryptoJournal',
    'CKC': u'Clockcoin',
    'CLAM': u'CLAMS',
    'CLICK': u'Clickcoin',
    'CLINT': u'Clinton',
    'CLOAK': u'CloakCoin',
    'CLR': u'CopperLark',
    'CLUB': u' ClubCoin',
    'CLUD': u'CludCoin',
    'CLV': u'CleverCoin',
    'CMC': u'CosmosCoin',
    'CMT': u'CometCoin',
    'CNC': u'ChinaCoin',
    'CNL': u'ConcealCoin',
    'CNMT': u'Coinomat',
    'CNO': u'Coino',
    'CNT': u'Centurion',
    'COC': u'Community Coin',
    'COIN': u'Coin',
    'COMM': u'Community Coin',
    'CON': u'Paycon',
    'COOL': u'CoolCoin',
    'CORAL': u'CoralPay',
    'COV': u'CovenCoin',
    'COVAL': u'Circuits of Value',
    'COX': u'CobraCoin',
    'CPC': u'CapriCoin',
    'CQST': u'ConquestCoin',
    'CRAB': u'CrabCoin',
    'CRACK': u'CrackCoin',
    'CRAFT': u'Craftcoin',
    'CRAIG': u'CraigsCoin',
    'CRAVE': u'CraveCoin',
    'CRBIT': u'Creditbit ',
    'CRC': u'CraftCoin',
    'CRE': u'Credits',
    'CREA': u'CreativeChain',
    'CREVA': u'Creva Coin',
    'CRNK': u'CrankCoin',
    'CRPS': u'CryptoPennies',
    'CRW': u'Crown Coin',
    'CRX': u'ChronosCoin',
    'CRYPT': u'CryptCoin',
    'CS': u'CryptoSpots',
    'CSC': u'CasinoCoin',
    'CSH': u'CashOut',
    'CSMIC': u'Cosmic',
    'CTC': u'CarterCoin',
    'CTIC': u'Coinmatic',
    'CTO': u'Crypto',
    'CUBE': u'DigiCube',
    'CURE': u'Curecoin',
    'CV2': u'ColossusCoin2.0',
    'CWXT': u'CryptoWorldXToken',
    'CXC': u'CheckCoin',
    'CXT': u'Coinonat',
    'CYC': u'ConSpiracy Coin ',
    'CYG': u'Cygnus',
    'CYP': u'CypherPunkCoin',
    'CYT': u'Cryptokenz',
    'DANK': u'DarkKush',
    'DAR': u'Darcrus',
    'DARK': u'Dark',
    'DASH': u'DigitalCash',
    'DB': u'DarkBit',
    'DBG': u'Digital Bullion Gold',
    'DBIC': u'DubaiCoin',
    'DBIX': u'DubaiCoin',
    'DBTC': u'DebitCoin',
    'DCC': u'DarkCrave',
    'DCK': u'DickCoin',
    'DCR': u'Decred',
    'DCRE': u'DeltaCredits',
    'DCT': u'Decent',
    'DCY': u'Dinastycoin',
    'DDF': u'Digital Developers Fund',
    'DEA': u'Degas Coin',
    'DEM': u'eMark',
    'DENT': u'Dent',
    'DES': u'Destiny',
    'DETH': u'DarkEther',
    'DEUR': u'DigiEuro',
    'DGB': u'DigiByte',
    'DGC': u'DigiCoin',
    'DGD': u'Digix DAO',
    'DGDC': u'DarkGold',
    'DGMS': u'Digigems',
    'DGORE': u'DogeGoreCoin',
    'DICE': u'Etheroll',
    'DIEM': u'CarpeDiemCoin',
    'DIGS': u'Diggits',
    'DIME': u'DimeCoin',
    'DISK': u'Dark Lisk',
    'DKC': u'DarkKnightCoin',
    'DLC': u'DollarCoin',
    'DLISK': u'Dlisk',
    'DMD': u'Diamond',
    'DNET': u'Darknet',
    'DOGE': u'Dogecoin',
    'DOGED': u'DogeCoinDark',
    'DOGETH': u'EtherDoge',
    'DOPE': u'DopeCoin',
    'DOT': u'Dotcoin',
    'DOV': u'DonationCoin',
    'DP': u'DigitalPrice',
    'DPAY': u'DelightPay',
    'DRA': u'DraculaCoin',
    'DRACO': u'DT Token',
    'DRKC': u'DarkCash',
    'DRKT': u'DarkTron',
    'DRM8': u'Dream8Coin',
    'DROP': u'FaucetCoin',
    'DRZ': u'Droidz',
    'DSB': u'DarkShibe',
    'DSH': u'Dashcoin',
    'DT': u'DarkToken',
    'DTB': u'Databits',
    'DTC': u'DayTrader Coin',
    'DUB': u'DubCoin',
    'DUCK': u'DuckDuckCoin',
    'DUO': u'ParallelCoin',
    'DUX': u'DuxCoin',
    'DVC': u'DevCoin',
    'DYN': u'Dynamic',
    'EA': u'EagleCoin',
    'EAC': u'EarthCoin',
    'EAGS': u'EagsCoin',
    'EB3': u'EB3coin',
    'EBS': u'EbolaShare',
    'EC': u'Eclipse',
    'ECO': u'ECOcoin',
    'ECOB': u'EcoBit',
    'EDC': u'EducoinV',
    'EDG': u'Edgeless',
    'EDGE': u'EdgeCoin',
    'EDR': u'E-Dinar Coin',
    'EDRC': u'EDRCoin',
    'EFL': u'E-Gulden',
    'EGC': u'EverGreenCoin',
    'EGG': u'EggCoin',
    'EGO': u'EGOcoin',
    'EKN': u'Elektron',
    'EKO': u'EkoCoin',
    'ELC': u'Elacoin',
    'ELE': u'Elementrem',
    'ELS': u'Elysium',
    'EMB': u'EmberCoin',
    'EMC': u'Emercoin',
    'EMC2': u'Einsteinium',
    'EMD': u'Emerald',
    'EMPC': u'EmporiumCoin',
    'ENE': u'EneCoin',
    'ENRG': u'EnergyCoin',
    'ENT': u'Eternity',
    'ENTER': u'EnterCoin (ENTER)',
    'EOC': u'EveryonesCoin',
    'EOS': u'EOS',
    'EPY': u'Empyrean',
    'EQM': u'Equilibrium Coin',
    'EQT': u'EquiTrader',
    'EQUAL': u'EqualCoin',
    'ERC': u'EuropeCoin',
    'ERR': u'ErrorCoin',
    'ERY': u'Eryllium',
    'ESP': u'Espers',
    'ETC': u'Ethereum Classic',
    'ETH': u'Ethereum ',
    'ETHS': u'EthereumScrypt',
    'EUC': u'Eurocoin',
    'EVENT': u'Event Token',
    'EVIL': u'EvilCoin',
    'EXB': u'ExaByte (EXB)',
    'EXCL': u'Exclusive Coin',
    'EXE': u'ExeCoin',
    'EXIT': u'ExitCoin',
    'EXP': u'Expanse',
    'EZC': u'EZCoin',
    'F16': u'F16Coin',
    'FAIR': u'FairCoin',
    'FAME': u'FameCoin',
    'FAZZ': u'FazzCoin',
    'FC2': u'Fuel2Coin',
    'FCN': u'FantomCoin ',
    'FCS': u'CryptoFocus',
    'FCT': u'Factoids',
    'FFC': u'FireflyCoin',
    'FGZ': u'Free Game Zone',
    'FIBRE': u'FIBRE',
    'FIND': u'FindCoin',
    'FIRE': u'FireCoin',
    'FIRST': u'FirstCoin',
    'FIST': u'FistBump',
    'FIT': u'Fitcoin',
    'FJC': u'FujiCoin',
    'FLDC': u'Folding Coin',
    'FLO': u'FlorinCoin',
    'FLT': u'FlutterCoin',
    'FLVR': u'FlavorCoin',
    'FLX': u'Flash',
    'FLY': u'FlyCoin',
    'FONZ': u'FonzieCoin',
    'FOREX': u'ForexCoin',
    'FRAC': u'FractalCoin',
    'FRC': u'FireRoosterCoin',
    'FRE': u'FreeCoin',
    'FRK': u'Franko',
    'FRN': u'Francs',
    'FRST': u'FirstCoin',
    'FRWC': u'Frankywillcoin',
    'FSC2': u'FriendshipCoin',
    'FSN': u'Fusion',
    'FST': u'FastCoin',
    'FTC': u'FeatherCoin',
    'FTP': u'FuturePoints',
    'FUN': u'FunFair',
    'FUNC': u'FunCoin',
    'FUTC': u'FutCoin',
    'FUZZ': u'Fuzzballs',
    'FX': u'FCoin',
    'FYN': u'FundYourselfNow',
    'GAIA': u'GAIA Platform',
    'GAKH': u'GAKHcoin',
    'GAM': u'Gambit coin',
    'GAME': u'Gamecredits',
    'GAP': u'Gapcoin',
    'GAY': u'GayCoin',
    'GB': u'GoldBlocks',
    'GBIT': u'GravityBit',
    'GBRC': u'GBR Coin',
    'GBT': u'GameBetCoin',
    'GBYTE': u'Byteball',
    'GCC': u'GuccioneCoin',
    'GCR': u'Global Currency Reserve',
    'GDC': u'GrandCoin',
    'GEMZ': u'Gemz Social',
    'GEN': u'Genstake',
    'GEO': u'GeoCoin',
    'GHC': u'GhostCoin',
    'GHOUL': u'Ghoul Coin',
    'GHS': u'Giga Hash',
    'GIFT': u'GiftNet',
    'GIG': u'GigCoin',
    'GIVE': u'GiveCoin',
    'GIZ': u'GIZMOcoin',
    'GLC': u'GlobalCoin',
    'GLD': u'GoldCoin',
    'GLOBE': u'Global',
    'GLX': u'GalaxyCoin',
    'GLYPH': u'GlyphCoin',
    'GMC': u'Gridmaster',
    'GML': u'GameLeagueCoin',
    'GMX': u'Goldmaxcoin',
    'GNJ': u'GanjaCoin V2',
    'GNO': u'Gnosis',
    'GNT': u'Golem Network Token',
    'GOAT': u'Goat',
    'GOLOS': u'Golos',
    'GOON': u'Goonies',
    'GOT': u'Giotto Coin',
    'GOTX': u'GothicCoin',
    'GP': u'GoldPieces',
    'GPL': u'Gold Pressed Latinum',
    'GPU': u'GPU Coin',
    'GRAM': u'Gram Coin',
    'GRAV': u'Graviton',
    'GRC': u'GridCoin',
    'GRE': u'GreenCoin',
    'GREXIT': u'GrexitCoin',
    'GRID': u'GridPay',
    'GRM': u'GridMaster',
    'GROW': u'GrownCoin',
    'GRS': u'Groestlcoin ',
    'GRT': u'Grantcoin',
    'GRW': u'GrowthCoin',
    'GSM': u'GSM Coin',
    'GSX': u'GlowShares',
    'GSY': u'GenesysCoin',
    'GUE': u'GuerillaCoin',
    'GUP': u'Guppy',
    'HAL': u'Halcyon',
    'HALLO': u'Halloween Coin',
    'HAMS': u'HamsterCoin',
    'HAZE': u'HazeCoin',
    'HBN': u'HoboNickels',
    'HCC': u'HappyCreatorCoin ',
    'HEAT': u'Heat Ledger',
    'HEDG': u'Hedgecoin',
    'HEEL': u'HeelCoin',
    'HILL': u'President Clinton',
    'HIRE': u'BitHIRE',
    'HKG': u'Hacker Gold',
    'HMP': u'HempCoin',
    'HMQ': u'Humaniq',
    'HNC': u'Hellenic Coin',
    'HODL': u'HOdlcoin',
    'HPC': u'HappyCoin',
    'HRB': u'Harbour DAO',
    'HSP': u'Horse Power',
    'HTC': u'Hitcoin',
    'HTML5': u'HTML Coin',
    'HUC': u'HunterCoin',
    'HUGE': u'BigCoin',
    'HUSH': u'Hush',
    'HVC': u'HeavyCoin',
    'HVCO': u'High Voltage Coin',
    'HXX': u'HexxCoin',
    'HYP': u'Hyperstake',
    'HYPER': u'HyperCoin',
    'HZ': u'Horizon',
    'HZT': u'HazMatCoin',
    'I0C': u'I0coin',
    'IBANK': u'iBankCoin',
    'ICASH': u'ICASH',
    'ICB': u'IceBergCoin',
    'ICN': u'Iconomi',
    'ICOB': u'Icobid',
    'ICON': u'Iconic',
    'IEC': u'IvugeoEvolutionCoin',
    'IFC': u'Infinite Coin',
    'IFLT': u'InflationCoin',
    'ILC': u'ILCoin',
    'IMPCH': u'Impeach',
    'IMPS': u'Impulse Coin',
    'IMS': u'Independent Money System',
    'IN': u'InCoin',
    'INC': u'Incrementum',
    'INCNT': u'Incent',
    'INCP': u'InceptionCoin',
    'INFX': u'Influxcoin',
    'INPAY': u'InPay',
    'INSANE': u'InsaneCoin',
    'INSN': u'Insane Coin',
    'INV': u'Invictus',
    'IOC': u'IOCoin',
    'ION': u'Ionomy',
    'IOP': u'Internet of People',
    'IOT': u'IOTA',
    'IOU': u'IOU1',
    'ISL': u'IslaCoin',
    'IVZ': u'InvisibleCoin',
    'IW': u'iWallet',
    'IXC': u'IXcoin',
    'IXT': u'InsureX',
    'J': u'JoinCoin',
    'JANE': u'JaneCoin',
    'JBS': u'JumBucks Coin',
    'JIF': u'JiffyCoin',
    'JIO': u'JIO Token',
    'JKC': u'JunkCoin',
    'JNS': u'Janus',
    'JOBS': u'JobsCoin',
    'JOK': u'JokerCoin',
    'JPC': u'JackPotCoin',
    'JUDGE': u'JudgeCoin',
    'JWL': u'Jewels',
    'KARM': u'Karmacoin',
    'KAT': u'KATZcoin',
    'KAYI': u'Kayı',
    'KC': u'Kernalcoin',
    'KDC': u'Klondike Coin',
    'KED': u'Klingon Empire Darsek',
    'KEY': u'KeyCoin',
    'KGC': u'KrugerCoin',
    'KLC': u'KiloCoin',
    'KMD': u'Komodo',
    'KNC': u'Khancoin',
    'KOBO': u'KoboCoin',
    'KORE': u'KoreCoin',
    'KR': u'Krypton',
    'KRAK': u'Kraken',
    'KRB': u'Karbowanec',
    'KRC': u'KRCoin',
    'KTK': u'KryptCoin',
    'KUBO': u'KubosCoin',
    'KURT': u'Kurrent',
    'KUSH': u'KushCoin',
    'LAB': u'CoinWorksCoin',
    'LANA': u'LanaCoin',
    'LAZ': u'Lazarus',
    'LBC': u'LBRY Credits',
    'LC': u'Lutetium Coin',
    'LDOGE': u'LiteDoge',
    'LEA': u'LeaCoin',
    'LEMON': u'LemonCoin',
    'LENIN': u'LeninCoin',
    'LEO': u'LEOcoin',
    'LEPEN': u'LePenCoin',
    'LFC': u'BigLifeCoin',
    'LGBTQ': u'LGBTQoin',
    'LGD': u'Legends Cryptocurrency',
    'LIMX': u'LimeCoinX',
    'LIR': u'Let it Ride',
    'LIV': u'LiviaCoin',
    'LK7': u'Lucky7Coin',
    'LKY': u'LuckyCoin',
    'LMC': u'LomoCoin',
    'LOC': u'Loco',
    'LOG': u'Wood Coin',
    'LOOK': u'LookCoin',
    'LQD': u'Liquid',
    'LSD': u'LightSpeedCoin',
    'LSK': u'Lisk',
    'LTB': u'Litebar ',
    'LTBC': u'LTBCoin',
    'LTC': u'Litecoin',
    'LTCD': u'LitecoinDark',
    'LTCR': u'LiteCreed',
    'LTCX': u'LitecoinX',
    'LTD': u'Limited Coin',
    'LTH': u'Lathaan',
    'LTS': u'Litestar Coin',
    'LUCKY': u'LuckyBlocks (LUCKY)',
    'LUN': u'Lunyr',
    'LUX': u'BitLux',
    'LVG': u'Leverage Coin',
    'LXC': u'LibrexCoin',
    'LYB': u'LyraBar',
    'LYC': u'LycanCoin',
    'M1': u'SupplyShock',
    'MAC': u'MachineCoin',
    'MAD': u'SatoshiMadness',
    'MAID': u'MaidSafe Coin',
    'MAPC': u'MapCoin',
    'MAR': u'MarijuanaCoin',
    'MARS': u'MarsCoin ',
    'MARV': u'Marvelous',
    'MARX': u'MarxCoin',
    'MARYJ': u'MaryJane Coin',
    'MAT': u'Manet Coin',
    'MAX': u'MaxCoin',
    'MBIT': u'Mbitbooks',
    'MCAP': u'MCAP',
    'MCAR': u'MasterCar',
    'MCN': u'MonetaVerde',
    'MCO': u'Monaco',
    'MCRN': u'MacronCoin',
    'MDC': u'MedicCoin',
    'MDT': u'Midnight ',
    'MEC': u'MegaCoin',
    'MED': u'MediterraneanCoin',
    'MEGA': u'MegaFlash',
    'MEME': u'Pepe',
    'MER': u'Mercury',
    'METAL': u'MetalCoin',
    'MG': u'Mind Gene',
    'MGO': u'MobileGo',
    'MI': u'XiaoMiCoin',
    'MIL': u'Milllionaire Coin',
    'MILO': u'MiloCoin',
    'MIN': u'Minerals Coin',
    'MINE': u'Instamine Nuggets',
    'MINT': u'MintCoin',
    'MIS': u'MIScoin',
    'MKR': u'Maker',
    'MLITE': u'MeLite',
    'MLN': u'Melon',
    'MM': u'MasterMint',
    'MMC': u'MemoryCoin',
    'MMNXT': u'MMNXT ',
    'MMXIV': u'MaieutiCoin',
    'MMXVI': u'MMXVI',
    'MN': u'Cryptsy Mining Contract',
    'MNC': u'MinCoin',
    'MND': u'MindCoin',
    'MNE': u'Minereum',
    'MNM': u'Mineum',
    'MOIN': u'MoinCoin',
    'MOJO': u'Mojocoin',
    'MONA': u'MonaCoin',
    'MONETA': u'Moneta',
    'MONEY': u'MoneyCoin',
    'MOON': u'MoonCoin',
    'MOOND': u'Dark Moon',
    'MOTO': u'Motocoin',
    'MPRO': u'MediumProject',
    'MRP': u'MorpheusCoin',
    'MRS': u'MarsCoin',
    'MRSA': u'MrsaCoin',
    'MRT': u'MinersReward',
    'MRY': u'MemoryCoin',
    'MSC': u'MasterCoin',
    'MST': u'MustangCoin',
    'MT': u'Mycelium Token',
    'MTL': u'Metal',
    'MTR': u'MasterTraderCoin',
    'MUDRA': u'MudraCoin',
    'MUE': u'MonetaryUnit',
    'MUSIC': u'Musiccoin',
    'MUU': u'MilkCoin',
    'MWC': u'MultiWallet Coin',
    'MXT': u'MartexCoin',
    'MYB': u'MyBit',
    'MYC': u'MayaCoin',
    'MYST': u'MysteryCoin',
    'MZC': u'MazaCoin',
    'N7': u'Number7',
    'NAN': u'NanoToken',
    'NANAS': u'BananaBits',
    'NAS2': u'Nas2Coin',
    'NAUT': u'Nautilus Coin',
    'NAV': u'NavCoin',
    'NBIT': u'NetBit',
    'NBL': u'Nybble',
    'NBT': u'NuBits',
    'NDOGE': u'NinjaDoge',
    'NEBU': u'Nebuchadnezzar',
    'NEC': u'NeoCoin',
    'NEF': u'NefariousCoin',
    'NEOS': u'NeosCoin',
    'NET': u'NetCoin',
    'NETC': u'NetworkCoin',
    'NETKO': u'Netko',
    'NEU': u'NeuCoin',
    'NEVA': u'NevaCoin',
    'NIC': u'NewInvestCoin',
    'NICE': u'NiceCoin',
    'NKA': u'IncaKoin',
    'NKC': u'Nukecoinz',
    'NKT': u'NakomotoDark',
    'NLC': u'NoLimitCoin',
    'NLG': u'Gulden',
    'NMB': u'Nimbus Coin',
    'NMC': u'NameCoin',
    'NMR': u'Numerai',
    'NOBL': u'NobleCoin',
    'NODE': u'Node',
    'NOO': u'Noocoin',
    'NOTE': u'Dnotes',
    'NPC': u'NPCcoin',
    'NRB': u'NoirBits',
    'NRC': u'Neurocoin',
    'NRS': u'NoirShares',
    'NSR': u'NuShares',
    'NTC': u'NineElevenTruthCoin',
    'NTCC': u'NeptuneClassic',
    'NTRN': u'Neutron',
    'NUBIS': u'NubisCoin',
    'NUKE': u'NukeCoin',
    'NUM': u'NumbersCoin',
    'NVC': u'NovaCoin',
    'NXC': u'Nexium',
    'NXE': u'NXEcoin',
    'NXS': u'Nexus',
    'NXT': u'Nxt',
    'NXTI': u'NXTI',
    'NXTTY': u'NXTTY',
    'NYAN': u'NyanCoin',
    'NZC': u'NewZealandCoin',
    'OAX': u'OpenANX',
    'OBITS': u'Obits Coin',
    'OBS': u'Obscurebay',
    'OC': u'OrangeCoin',
    'OCTO': u'OctoCoin',
    'ODNT': u'Old Dogs New Tricks',
    'OK': u'OKCash',
    'OLDSF': u'OldSafeCoin',
    'OLYMP': u'OlympCoin',
    'OMA': u'OmegaCoin',
    'OMC': u'OmniCron',
    'OMNI': u'Omni',
    'OPAL': u'OpalCoin',
    'OPES': u'Opes',
    'OPTION': u'OptionCoin',
    'ORB': u'Orbitcoin',
    'ORLY': u'OrlyCoin',
    'ORO': u'OroCoin',
    'OS76': u'OsmiumCoin',
    'OSC': u'OpenSourceCoin',
    'PAC': u'PacCoin',
    'PAK': u'Pakcoin',
    'PARA': u'ParanoiaCoin',
    'PASC': u'Pascal Coin',
    'PASL': u'Pascal Lite',
    'PAY': u'TenX',
    'PAYP': u'PayPeer',
    'PBC': u'PabyosiCoin',
    'PCM': u'Procom',
    'PCS': u'Pabyosi Coin',
    'PDC': u'Project Decorum',
    'PEC': u'PeaceCoin',
    'PEN': u'PenCoin',
    'PEPECASH': u'Pepe Cash',
    'PEX': u'PosEx',
    'PHR': u'Phreak',
    'PHS': u'PhilosophersStone',
    'PIE': u'Persistent Information Exchange',
    'PIGGY': u'Piggy Coin',
    'PING': u'CryptoPing',
    'PINK': u'PinkCoin',
    'PINKX': u'PantherCoin',
    'PIO': u'Pioneershares',
    'PIVX': u'Private Instant Verified Transaction',
    'PIZZA': u'PizzaCoin',
    'PKB': u'ParkByte',
    'PLANET': u'PlanetCoin',
    'PLBT': u'Polybius',
    'PLNC': u'PLNCoin',
    'PLU': u'Pluton',
    'PNC': u'PlatiniumCoin',
    'PND': u'PandaCoin',
    'PNK': u'SteamPunk',
    'POINTS': u'Cryptsy Points',
    'POLY': u'PolyBit',
    'POST': u'PostCoin',
    'POSW': u'PoSWallet',
    'POT': u'PotCoin',
    'PPC': u'PeerCoin',
    'PPT': u'Populous',
    'PPY': u'Peerplays',
    'PRC': u'ProsperCoin',
    'PRE': u'Premium',
    'PRES': u'President Trump',
    'PRIME': u'PrimeChain',
    'PRM': u'PrismChain',
    'PROC': u'ProCurrency',
    'PRX': u'Printerium',
    'PSB': u'PesoBit',
    'PSEUD': u'PseudoCash',
    'PSI': u'PSIcoin',
    'PSY': u'Psilocybin',
    'PTA': u'PentaCoin',
    'PTC': u'PesetaCoin',
    'PTOY': u'Patientory',
    'PTS': u'Protoshares',
    'PULSE': u'Pulse',
    'PUPA': u'PupaCoin',
    'PUT': u'PutinCoin',
    'PWR': u'PowerCoin',
    'PX': u'PXcoin',
    'PXC': u'PhoenixCoin',
    'PXI': u'Prime-X1',
    'PXL': u'Phalanx',
    'PYC': u'PayCoin',
    'QAU': u'Quantum',
    'QBC': u'Quebecoin',
    'QBK': u'QuBuck Coin',
    'QBT': u'Cubits',
    'QCN': u'Quazar Coin',
    'QORA': u'QoraCoin',
    'QRK': u'QuarkCoin',
    'QRL': u'Quantum Resistant Ledger',
    'QSLV': u'Quicksilver coin',
    'QTL': u'Quatloo',
    'QTUM': u'QTUM',
    'QTZ': u'Quartz',
    'QWARK': u'Qwark',
    'RADI': u'RadicalCoin',
    'RADS': u'Radium',
    'RAIN': u'Condensate',
    'RATIO': u'Ratio',
    'RBIES': u'Rubies',
    'RBIT': u'ReturnBit',
    'RBR': u'Ribbit Rewards',
    'RBT': u'Rimbit',
    'RBX': u'RiptoBuX',
    'RBY': u'RubyCoin',
    'RC': u'Russiacoin',
    'RCN': u'RCoin',
    'RCX': u'RedCrowCoin',
    'RDD': u'ReddCoin',
    'RDN': u'RadonPay',
    'RED': u'Redcoin',
    'REE': u'ReeCoin',
    'REP': u'Augur',
    'REV': u'Revenu',
    'RIC': u'Riecoin',
    'RICE': u'RiceCoin',
    'RIDE': u'Ride My Car',
    'RING': u'RingCoin',
    'RIPO': u'RipOffCoin',
    'RISE': u'Rise',
    'RLC': u'iEx.ec',
    'RMS': u'Resumeo Shares',
    'RNC': u'ReturnCoin',
    'RNS': u'RenosCoin',
    'ROOT': u'RootCoin',
    'ROS': u'ROS Coin',
    'ROUND': u'RoundCoin',
    'ROYAL': u'RoyalCoin',
    'RPC': u'RonPaulCoin',
    'RRT': u'Recovery Right Tokens',
    'RT2': u'RotoCoin',
    'RUBIT': u'Rublebit',
    'RUST': u'RustCoin',
    'RYC': u'RoyalCoin',
    'RYCN': u'RoyalCoin 2.0',
    'RZR': u'RazorCoin',
    'S8C': u'S88 Coin',
    'SAK': u'SharkCoin',
    'SAN': u'Santiment',
    'SANDG': u'Save and Gain',
    'SAR': u'SARCoin',
    'SAT2': u'Saturn2Coin',
    'SBC': u'StableCoin',
    'SBD': u'Steem Backed Dollars',
    'SC': u'Siacoin',
    'SCASH': u'SpaceCash',
    'SCN': u'Swiscoin',
    'SCOT': u'Scotcoin',
    'SCRPT': u'ScryptCoin',
    'SCRT': u'SecretCoin',
    'SCT': u'ScryptToken',
    'SDC': u'ShadowCash',
    'SDP': u'SydPakCoin',
    'SEC': u'SafeExchangeCoin',
    'SEEDS': u'SeedShares',
    'SEL': u'SelenCoin',
    'SEN': u'Sentaro',
    'SEQ': u'Sequence',
    'SFC': u'Solarflarecoin',
    'SFE': u'Safecoin',
    'SFR': u'SaffronCoin',
    'SH': u'Shilling',
    'SHADE': u'ShadeCoin',
    'SHIFT': u'Shift',
    'SHLD': u'ShieldCoin',
    'SHORTY': u'ShortyCoin',
    'SIB': u'SibCoin',
    'SIGU': u'Singular',
    'SILK': u'SilkCoin',
    'SJCX': u'StorjCoin',
    'SKB': u'SkullBuzz',
    'SKY': u'Skycoin',
    'SLG': u'SterlingCoin',
    'SLING': u'Sling Coin',
    'SLM': u'SlimCoin',
    'SLR': u'SolarCoin',
    'SLS': u'SaluS',
    'SMAC': u'Social Media Coin',
    'SMC': u'SmartCoin',
    'SMF': u'SmurfCoin',
    'SMLY': u'SmileyCoin',
    'SMSR': u'Samsara Coin',
    'SNC': u'SunContract',
    'SNGLS': u'SingularDTV',
    'SNM': u'SONM',
    'SNRG': u'Synergy',
    'SNT': u'Status Network Token',
    'SOIL': u'SoilCoin',
    'SOLE': u'SoleCoin',
    'SONG': u'Song Coin',
    'SOON': u'SoonCoin',
    'SOUL': u'SoulCoin',
    'SP': u'Sex Pistols',
    'SPA': u'SpainCoin',
    'SPACE': u'SpaceCoin',
    'SPC': u'SpinCoin',
    'SPEC': u'SpecCoin',
    'SPHR': u'Sphere Coin',
    'SPKTR': u'Ghost Coin',
    'SPM': u'Supreme',
    'SPORT': u'SportsCoin',
    'SPOTS': u'Spots',
    'SPR': u'Spreadcoin',
    'SPRTS': u'Sprouts',
    'SPT': u'Spots',
    'SPX': u'Specie',
    'SQL': u'Squall Coin',
    'SRC': u'SecureCoin',
    'SSD': u'Sonic Screw Driver Coin',
    'SSTC': u'SunShotCoin',
    'SSV': u'SSVCoin',
    'STA': u'Stakers',
    'STALIN': u'StalinCoin',
    'STAR': u'StarCoin',
    'START': u'StartCoin',
    'STEEM': u'Steem',
    'STEPS': u'Steps',
    'STHR': u'Stakerush',
    'STO': u'Save The Ocean',
    # 'STR*': u'StarCoin',
    'STRAT': u'Stratis',
    'STS': u'STRESScoin',
    'STV': u'Sativa Coin',
    'SUB': u'Subscriptio',
    'SUP': u'Supcoin',
    'SUPER': u'SuperCoin',
    'SUR': u'Suretly',
    'SWARM': u'SwarmCoin',
    'SWEET': u'SweetStake',
    'SWIFT': u'BitSwift',
    'SWING': u'SwingCoin',
    'SWT': u'Swarm City Token',
    'SXC': u'SexCoin',
    'SYNC': u'SyncCoin',
    'SYNX': u'Syndicate',
    'SYS': u'SysCoin',
    'TAAS': u'Token as a Service',
    'TAB': u'MollyCoin',
    'TAG': u'TagCoin',
    'TAGR': u'Think And Get Rich Coin',
    'TAJ': u'TajCoin',
    'TAK': u'TakCoin',
    'TAM': u'TamaGucci',
    'TAP': u'TappingCoin',
    'TBCX': u'TrashBurn',
    'TCR': u'Thecreed',
    'TDFB': u'TDFB',
    'TEAM': u'TeamUP',
    'TEC': u'TeCoin',
    'TECH': u'TechCoin',
    'TEK': u'TekCoin',
    'TELL': u'Tellurion',
    'TENNET': u'Tennet',
    'TES': u'TeslaCoin',
    'TESLA': u'TeslaCoilCoin',
    'TFL': u'True Flip Lottery',
    'TGC': u'TigerCoin',
    'THC': u'The Hempcoin',
    'THS': u'TechShares',
    'TIA': u'Tianhe',
    'TIC': u'TrueInvestmentCoin',
    'TIME': u'Time',
    'TIT': u'TitCoin',
    'TIX': u'Blocktix',
    'TKN': u'TokenCard  ',
    'TKS': u'Tokes',
    'TMC': u'TimesCoin',
    'TODAY': u'TodayCoin',
    'TOR': u'TorCoin',
    'TOT': u'TotCoin',
    'TPAY': u'TrollPlay',
    'TPG': u'Troll Payment',
    'TRA': u'Tetra',
    'TRC': u'TerraCoin',
    'TRI': u'Triangles Coin',
    'TRICK': u'TrickyCoin',
    'TRIG': u'Trigger',
    'TRK': u'TruckCoin',
    'TRON': u'Positron',
    'TRST': u'TrustCoin',
    'TRUMP': u'TrumpCoin',
    'TRUST': u'TrustPlus',
    'TSE': u'TattooCoin',
    'TTC': u'TittieCoin',
    'TUR': u'Turron',
    'TWIST': u'TwisterCoin',
    'TWLV': u'Twelve Coin',
    'TX': u'Transfer',
    'U': u'Ucoin',
    'UBIQ': u'Ubiqoin',
    'UBQ': u'Ubiq',
    'UFO': u'UFO Coin',
    'UIS': u'Unitus',
    'ULTC': u'Umbrella',
    'UNAT': u'Unattanium',
    'UNB': u'UnbreakableCoin',
    'UNC': u'UnCoin',
    'UNF': u'Unfed Coin',
    'UNI': u'Universe',
    'UNIQ': u'Uniqredit',
    'UNIT': u'Universal Currency',
    'UNITS': u'GameUnits',
    'UNITY': u'SuperNET',
    'UNO': u'Unobtanium',
    'UR': u'UR',
    'URO': u'UroCoin',
    'USC': u'Ultimate Secure Cash',
    'USDE': u'UnitaryStatus Dollar',
    'USDT': u'Tether',
    'UTC': u'UltraCoin',
    'UTH': u'Uther',
    'UTIL': u'Utility Coin',
    'VAPOR': u'Vaporcoin',
    'VDO': u'VidioCoin',
    'VEC2': u'VectorCoin 2.0 ',
    'VEG': u'BitVegan',
    'VERI': u'Veritaseum',
    'VERSA': u'Versa Token',
    'VIA': u'ViaCoin',
    'VIDZ': u'PureVidz',
    'VIOR': u'ViorCoin',
    'VIP': u'VIP Tokens',
    'VIRAL': u'Viral Coin',
    'VISIO': u'Visio',
    'VLT': u'Veltor',
    'VLTC': u'VaultCoin',
    'VMC': u'VirtualMining Coin',
    'VOLT': u'BitVolt',
    'VOOT': u'VootCoin',
    'VOX': u'Voxels',
    'VOYA': u'Voyacoin',
    'VPRC': u'VapersCoin',
    'VRC': u'VeriCoin',
    'VRM': u'Verium',
    'VRS': u'Veros',
    'VSL': u'vSlice',
    'VTA': u'VirtaCoin',
    'VTC': u'VertCoin',
    'VTR': u'Vtorrent',
    'VTX': u'Vertex',
    'VTY': u'Victoriouscoin',
    'VUC': u'Virta Unique Coin',
    'WARP': u'WarpCoin',
    'WASH': u'WashingtonCoin',
    'WAVES': u'Waves',
    'WAY': u'WayCoin',
    'WBB': u'Wild Beast Coin',
    'WBTC': u'wBTC',
    'WC': u'WhiteCoin',
    'WCT': u'Waves Community Token',
    'WDC': u'WorldCoin',
    'WEALTH': u'WealthCoin',
    'WEX': u'Wexcoin',
    'WGC': u'World Gold Coin',
    'WGO': u'WavesGO',
    'WGR': u'Wagerr',
    'WINE': u'WineCoin',
    'WINGS': u'Wings DAO',
    'WISC': u'WisdomCoin',
    'WMC': u'WMCoin',
    'WOLF': u'Insanity Coin',
    'WOP': u'WorldPay',
    'WRC': u'WarCoin',
    'WSX': u'WeAreSatoshi',
    'WTT': u'Giga Watt',
    'X2': u'X2Coin',
    'XAI': u'SapienceCoin',
    'XAU': u'XauCoin',
    'XAUR': u'Xaurum',
    'XBC': u'BitcoinPlus',
    'XBOT': u'SocialXbotCoin',
    'XBS': u'Bitstake',
    'XBTS': u'Beats',
    'XBY': u'XtraBYtes',
    'XC': u'X11 Coin',
    'XCASH': u'Xcash',
    'XCE': u'Cerium',
    'XCI': u'Cannabis Industry Coin',
    'XCN': u'Cryptonite',
    'XCO': u'XCoin',
    'XCP': u'CounterParty',
    'XCR': u'Crypti',
    'XCRE': u'Creatio',
    'XCT': u'C-Bits',
    'XDB': u'DragonSphere',
    'XDE2': u'XDE II',
    'XDN': u'DigitalNote ',
    'XDP': u'DogeParty',
    'XDQ': u'Dirac Coin',
    'XEL': u'Elastic',
    'XEM': u'NEM',
    'XEN': u'XenixCoin',
    'XFC': u'Forever Coin',
    'XG': u'XG Sports',
    'XGB': u'GoldenBird',
    'XGR': u'GoldReserve',
    'XHI': u'HiCoin',
    'XID': u'International Diamond Coin',
    'XJO': u'JouleCoin',
    'XLB': u'LibertyCoin',
    'XLM': u'Stellar',
    'XLR': u'Solaris',
    'XMG': u'Coin Magi',
    'XMR': u'Monero',
    'XMS': u'Megastake',
    'XMY': u'MyriadCoin',
    'XNA': u'DeOxyRibose',
    'XNC': u'Numismatic Collections',
    'XNG': u'Enigma',
    'XNX': u'XanaxCoin',
    'XPB': u'Pebble Coin',
    'XPD': u'PetroDollar',
    'XPH': u'PharmaCoin',
    'XPM': u'PrimeCoin',
    'XPO': u'Opair',
    'XPOKE': u'PokeChain',
    'XPRO': u'ProCoin',
    'XPS': u'PoisonIvyCoin',
    'XPY': u'PayCoin',
    'XQN': u'Quotient',
    'XRA': u'Ratecoin',
    'XRB': u'RaiBlocks',
    'XRE': u'RevolverCoin',
    'XRL': u'Rialto.AI',
    'XRP': u'Ripple',
    'XSEED': u'BitSeeds',
    'XSI': u'Stability Shares',
    'XSP': u'PoolStamp',
    'XSPEC': u'Spectre',
    'XST': u'StealthCoin',
    'XT': u'ExtremeCoin',
    'XTC': u'TileCoin',
    'XTZ': u'Tezos',
    'XUP': u'UPcoin',
    'XVC': u'Vcash',
    'XVE': u'The Vegan Initiative',
    'XVG': u'Verge',
    'XVP': u'VirtacoinPlus',
    'XVS': u'Vsync',
    'XWC': u'WhiteCoin',
    'XWT': u'World Trade Funds',
    'XXX': u'XXXCoin',
    'XZC': u'ZCoin',
    'YAC': u'YAcCoin',
    'YAY': u'YAYcoin',
    'YBC': u'YbCoin',
    'YES': u'YesCoin',
    'YMC': u'YamahaCoin',
    'YOC': u'YoCoin',
    'YOVI': u'YobitVirtualCoin',
    'ZBC': u'Zilbercoin',
    'ZCC': u'ZCC Coin',
    'ZCL': u'ZClassic',
    'ZEC': u'ZCash',
    'ZECD': u'ZCashDarkCoin',
    'ZED': u'ZedCoins',
    'ZEIT': u'ZeitCoin',
    'ZEN': u'ZenCash',
    'ZENI': u'Zennies',
    'ZER': u'Zero',
    'ZET': u'ZetaCoin',
    'ZET2': u'Zeta2Coin',
    'ZLQ': u'ZLiteQubit',
    'ZNE': u'ZoneCoin',
    'ZNY': u'BitZeny',
    'ZOI': u'Zoin',
    'ZOOM': u'ZoomCoin',
    'ZRC': u'ZrCoin',
    'ZSE': u'ZSEcoin',
    'ZUR': u'Zurcoin',
    'ZXT': u'Zcrypt',
    'ZYD': u'ZayedCoin',
}

# ----------------------------------------------------------------------
# Help/support URLs
# ----------------------------------------------------------------------
HELP_URL = 'https://github.com/deanishe/alfred-convert/issues'
README_URL = 'https://github.com/deanishe/alfred-convert#alfred-convert'

# ----------------------------------------------------------------------
# Icons
# ----------------------------------------------------------------------
ICON_CURRENCY = 'icons/money.png'
ICON_HELP = 'icons/help.png'
ICON_UPDATE = 'icons/update-available.png'

# ----------------------------------------------------------------------
# Update and default user settings
# ----------------------------------------------------------------------
UPDATE_SETTINGS = {'github_slug': 'deanishe/alfred-convert'}
DEFAULT_SETTINGS = {}


def bootstrap(wf):
    """Copy default files to user data if necessary.

    Args:
        wf (Workflow3): Active `Workflow3` object.

    """
    filepaths = [
        (wf.datafile(CUSTOM_DEFINITIONS_FILENAME),
         wf.workflowfile(CUSTOM_DEFINITIONS_FILENAME + '.sample')),
        (wf.datafile(ACTIVE_CURRENCIES_FILENAME),
         wf.workflowfile(ACTIVE_CURRENCIES_FILENAME + '.default')),
    ]

    for path, default in filepaths:
        if not os.path.exists(path):
            shutil.copy(default, path)
